import { nanoid } from "nanoid";
import type { Chat, Message, Output } from "@/types";
import { useChatStore } from "@/stores/useChatStore";
import { useBuildStore } from "@/stores/useBuildStore";
import { useWorkspaceStore } from "@/stores/useWorkspaceStore";
import { mockBuildFromOutput } from "@/lib/build-project/mock-build-from-output";

/**
 * Seed a freshly-created Mobile space so the user lands on a working demo
 * instead of an empty "No chats yet" screen.
 *
 * Produces:
 *  - 1 chat (one user prompt + one assistant reply)
 *  - 1 exploration approach output (kept to canvas)
 *  - 1 Built mobile output (kept to canvas) backed by a real BuildProject
 *    with `snackSource` so the On Device tab + Build preview both have content
 *
 * Side-effect: opens the workspace's On Device tab + share overlay so the
 * mobile preview surface is the first thing the user sees (the wow moment).
 *
 * Web spaces are unaffected — only call this when `targetPlatform === "mobile"`.
 *
 * Returns the seeded chat so callers can navigate directly to it.
 */
export function seedMobileSpaceDemo(spaceId: string): Chat {
  const now = new Date().toISOString();
  const chatId = `chat-${nanoid(6)}`;
  const userMsgId = `msg-${nanoid(6)}`;
  const aiMsgId = `msg-${nanoid(6)}`;
  const explorationOutputId = `out-${nanoid(6)}`;
  const builtOutputId = `out-${nanoid(6)}`;

  const explorationOutput: Output = {
    id: explorationOutputId,
    messageId: aiMsgId,
    chatId,
    spaceId,
    shellId: null,
    type: "approach",
    fidelity: "exploration",
    title: "Daily activity tracker",
    summary:
      "Home tab anchored on today: a hero progress ring, recent activity cards, and a thumb-reach 'Log workout' CTA.",
    content:
      "# Daily activity tracker\n\nFocus the home tab on **today**: a hero ring (steps + active minutes), three recent activity cards, and a primary 'Log workout' CTA that lives within thumb reach.\n\n## Key screens\n- Home — today's ring + recent + log CTA\n- Activity — chronological feed\n- Profile — streaks + settings\n\n## Why this works on mobile\n- Big tap targets in the lower 60% of the screen\n- Hero stat is glanceable from a lock-screen widget\n- Tab bar instead of a drawer — no chrome battles",
    kept: true,
    keptAt: now,
    canvasPosition: { x: 100, y: 100 },
    platform: "mobile",
  };

  // Mock-build off the same source so snackSource is generated by the canonical builder.
  const buildSeedOutput: Output = {
    ...explorationOutput,
    id: builtOutputId,
    fidelity: "built",
  };
  const buildProject = mockBuildFromOutput(buildSeedOutput);

  const builtOutput: Output = {
    id: builtOutputId,
    messageId: aiMsgId,
    chatId,
    spaceId,
    shellId: null,
    type: "screen",
    fidelity: "built",
    title: "Activity tracker · Built",
    summary:
      "Mock RN scaffold (Home tab + activity cards + bottom tab bar). Live in the Mobile preview.",
    content: explorationOutput.content,
    kept: true,
    keptAt: now,
    canvasPosition: { x: 600, y: 100 },
    platform: "mobile",
    buildProjectId: buildProject.id,
  };

  const messages: Message[] = [
    {
      id: userMsgId,
      chatId,
      role: "user",
      content:
        "Kick this space off with a daily activity tracker — start with a home screen I can preview on my phone.",
      outputs: [],
      contextItemIds: [],
      timestamp: now,
    },
    {
      id: aiMsgId,
      chatId,
      role: "assistant",
      content:
        "Here's an exploration plus a working mobile scaffold. Open the Mobile tab to scan the QR or watch live updates from your phone.",
      outputs: [explorationOutput, builtOutput],
      contextItemIds: [],
      timestamp: now,
    },
  ];

  const chat: Chat = {
    id: chatId,
    spaceId,
    shellId: null,
    name: "Activity tracker — kickoff",
    createdAt: now,
    updatedAt: now,
    messages,
  };

  // Insert chat into the chat store and mark it active so navigation lands on it.
  useChatStore.setState((state) => ({
    chats: [...state.chats, chat],
    activeChatId: chat.id,
  }));

  // Register the build project so OnDevicePanel + BuildPreviewPanel can resolve it.
  useBuildStore.getState().upsertProject(buildProject);

  // Open the On Device tab + share overlay — the mobile preview is the wow moment.
  useWorkspaceStore.getState().openOnDeviceTab();

  return chat;
}
